name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ls
            cd Jambaram-Web
            git pull
            cd jambaram
            export NVM_DIR=~/.nv
            source ~/.nvm/nvm.sh
            npm --help
            npm install
            npm run build
